#!/usr/bin/env python3

import argparse
import csv
import json
import sys

def main():
    parser = argparse.ArgumentParser(description="Converts dsv from stdin to json on stdout")
    parser.add_argument('DELIMITER', help="The delimiter separating values" )
    args = parser.parse_args()

    delimiter = args.DELIMITER
    lines = sys.stdin.readlines()
    cells = list(map(lambda l: l.strip("\n").split(delimiter), lines))
    print(json.dumps(cells))
    exit(0)

if __name__ == "__main__":
    main()
