#!/usr/bin/env python3

import argparse
import csv
import json
import sys

def main():
    parser = argparse.ArgumentParser(description="Converts json on stdin to dsv on stdout")
    args = parser.parse_args()

    rows = json.load(sys.stdin)
    delimiter = sys.argv[1]
    for row in rows:
        print(delimiter.join(row))
    exit(0)

if __name__ == "__main__":
    main()
