#!/usr/bin/env python3

import argparse
import csv
import json
import sys
import yaml

def main():
    parser = argparse.ArgumentParser(description="Converts json from stdin to yaml on stdout")
    args = parser.parse_args()

    print(yaml.dump(json.load(sys.stdin), default_flow_style=False), end='')
    exit(0)

if __name__ == "__main__":
    main()
