#!/usr/bin/env python3

import argparse
import json
import sys
import urllib
import urllib.request

def tuples_to_dict(tuples):
    return {i[0]: i[1] for i in tuples}

def make_request(url, body):
    request = urllib.request.Request(
            url=url,
            data=json.dumps(body).encode("UTF-8"),
            headers={
                "Content-Type": "application/json"
            },
            method='POST')
    try:
        response = urllib.request.urlopen(request)
        response_dict = {
        "status": response.status,
        "body": response.read().decode("ASCII"),
        "headers": tuples_to_dict(response.getheaders()),
    }
    except urllib.error.URLError as e:
        response_dict = {
            "status": e.code,
            "body": e.reason,
            "headers": tuples_to_dict(e.headers.items()),
    }

    if response_dict["status"] < 400:
        exit_code = 0
    else:
        exit_code = 1

    return json.dumps(response_dict), exit_code

def main():
    parser = argparse.ArgumentParser(description="Posts the json in stdin to the URL")
    parser.add_argument('URL', help="The url to which to post the json")
    args = parser.parse_args()

    body = json.load(sys.stdin)
    stdout, exit_code = make_request(args.URL, body)

    print(stdout)
    exit(exit_code)

if __name__ == "__main__":
    main()

