#!/usr/bin/env python3

import argparse
import csv
import json
import sys

def main():
    parser = argparse.ArgumentParser(description="Converts json on stdin to csv on stdout")
    args = parser.parse_args()

    rows = json.load(sys.stdin)
    csv_writer = csv.writer(sys.stdout, dialect='unix')
    csv_writer.writerows(rows)
    exit(0)

if __name__ == "__main__":
    main()
