#!/usr/bin/env python3

import argparse
import json
import sys
import xmltodict

def main():
    parser = argparse.ArgumentParser(description="Converts xml from stdin to json on stdout")
    args = parser.parse_args()

    xml_string = sys.stdin.read()
    print(json.dumps(xmltodict.parse(xml_string)))
    exit(0)

if __name__ == "__main__":
    main()
